on:
  push:
    paths:
      - "src/**/*"
      - "package.json"

name: build

jobs:

  build:
    name: Build from source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - run: npm install
      - uses: Adzz/jest_test_action@v2.0.0
        with:
          command: build:check

